# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: NISZ.AlairoAlkalmazas_KEAASZ
PackageVersion: 1.33.0
PackageLocale: hu-HU
Publisher: NISZ
PackageName: Kormanyzati Elektronikus Alairo es Alairas-ellenorzo Szoftver
License: Propriatery
ShortDescription: KEAASZ
Moniker: KEAASZ
Tags:
- eszemelyi
- eszig
ManifestType: defaultLocale
ManifestVersion: 1.0.0

